org.gradle.jvmargs=--enable-native-access=ALL-UNNAMED -Xmx4096M
systemProp.jdk.java.options=--enable-native-access=ALL-UNNAMED
systemProp.java.tool.options=--enable-native-access=ALL-UNNAMED
android.prefabVersion=2.0.0
org.gradle.parallel=true
unityStreamingAssets=
unityTemplateVersion=25
unityProjectPath=D:/gamer/proj/unity/u3d-learn2
unity.projectPath=D:/gamer/proj/unity/u3d-learn2
unity.debugSymbolLevel=none
unity.buildToolsVersion=36.0.0
unity.minSdkVersion=26
unity.targetSdkVersion=36
unity.compileSdkVersion=35
unity.applicationId=com.UnityTechnologies.com.unity.template.urpblank
unity.abiFilters=arm64-v8a
unity.versionCode=1
unity.versionName=0.1.0
unity.namespace=com.UnityTechnologies.com.unity.template.urpblank
unity.agpVersion=9.0.0
unity.androidSdkPath=C\:/Softwares/UnityHub/Editor/6000.6.2f1/Editor/Data/PlaybackEngines/AndroidPlayer/SDK
unity.androidNdkPath=C\:/Softwares/UnityHub/Editor/6000.6.2f1/Editor/Data/PlaybackEngines/AndroidPlayer/NDK
unity.androidNdkVersion=27.2.12479018
unity.jdkPath=C\:/Softwares/UnityHub/Editor/6000.6.2f1/Editor/Data/PlaybackEngines/AndroidPlayer/OpenJDK
unity.javaCompatibilityVersion=VERSION_17
unity.javaCompatabilityVersion=VERSION_17
unity.installInBuildFolder=false
android.useAndroidX=true
android.enableJetifier=true
android.builtInKotlin=false
android.r8.strictFullModeForKeepRules=false
android.bundle.includeNativeDebugMetadata=false
org.gradle.welcome=never
# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
